import { readFileSync } from "node:fs";
import Split from "../src/core/preTokenizer/Split";
import { legacyProblematicRegexPatternIds, splitRegexCaseByName } from "./utils/splitRegexCases";

type OracleCase = {
  name: string;
  patternId: string;
  expected: Array<{
    input: string;
    tokens: string[];
  }>;
};

type OracleFixture = {
  tokenizersVersion: string;
  cases: OracleCase[];
};

const fixture = JSON.parse(readFileSync(new URL("./fixtures/splitRegexOracle.json", import.meta.url), "utf8")) as OracleFixture;

describe(`Split regex oracle generated by Python tokenizers ${fixture.tokenizersVersion}`, () => {
  it("includes legacy problematic regex compatibility cases", () => {
    const oraclePatternIds = new Set(fixture.cases.map(({ patternId }) => patternId));

    for (const patternId of legacyProblematicRegexPatternIds) {
      expect(oraclePatternIds.has(patternId)).toBe(true);
    }
  });

  it.each(fixture.cases)("matches Python Split output: $name", (oracleCase) => {
    const testCase = splitRegexCaseByName.get(oracleCase.name);
    expect(testCase).toBeDefined();
    expect(testCase!.patternId).toBe(oracleCase.patternId);

    const preTokenizer = new Split({
      type: "Split",
      pattern: { Regex: testCase!.pattern },
      behavior: testCase!.behavior,
      invert: testCase!.invert,
    });

    for (const { input, tokens } of oracleCase.expected) {
      expect(preTokenizer.pre_tokenize_text(input)).toEqual(tokens);
    }
  });
});
