import { readFileSync } from "node:fs";
import Split from "../src/core/preTokenizer/Split";

import type { TokenizerConfigPreTokenizerSplit } from "../src/static/tokenizer";

type OracleCase = {
  name: string;
  pattern: string;
  behavior: TokenizerConfigPreTokenizerSplit["behavior"];
  invert: boolean;
  expected: Array<{
    input: string;
    tokens: string[];
  }>;
};

type OracleFixture = {
  tokenizersVersion: string;
  cases: OracleCase[];
};

const fixture = JSON.parse(readFileSync(new URL("./fixtures/splitRegexOracle.json", import.meta.url), "utf8")) as OracleFixture;

describe(`Split regex oracle generated by Python tokenizers ${fixture.tokenizersVersion}`, () => {
  it.each(fixture.cases)("matches Python Split output: $name", (testCase) => {
    const preTokenizer = new Split({
      type: "Split",
      pattern: { Regex: testCase.pattern },
      behavior: testCase.behavior,
      invert: testCase.invert,
    });

    for (const { input, tokens } of testCase.expected) {
      expect(preTokenizer.pre_tokenize_text(input)).toEqual(tokens);
    }
  });
});
