import { readFileSync } from "node:fs";
import { gunzipSync } from "node:zlib";
import Split from "../src/core/preTokenizer/Split";

import type { TokenizerConfigPreTokenizerSplit } from "../src/static/tokenizer";

type OracleCase = {
  name: string;
  patternId: string;
  pattern: string;
  behavior: TokenizerConfigPreTokenizerSplit["behavior"];
  invert: boolean;
  knownDivergence: boolean;
  expected: Array<{
    input: string;
    tokens: string[];
  }>;
};

type OracleFixture = {
  tokenizersVersion: string;
  source: string;
  cases: OracleCase[];
};

// The oracle is committed gzipped (see tests/py/generate_split_regex_oracle.py) to avoid a
// large generated text file in git; decompress it here.
const fixture = JSON.parse(gunzipSync(readFileSync(new URL("./fixtures/splitRegexOracle.json.gz", import.meta.url))).toString("utf8")) as OracleFixture;
const patternsFixture = JSON.parse(readFileSync(new URL("./fixtures/splitRegexPatterns.json", import.meta.url), "utf8")) as { patterns: Array<{ id: string }> };

const create_split = (oracleCase: OracleCase) =>
  new Split({
    type: "Split",
    pattern: { Regex: oracleCase.pattern },
    behavior: oracleCase.behavior,
    invert: oracleCase.invert,
  });

describe(`Split regex oracle generated by Python tokenizers ${fixture.tokenizersVersion}`, () => {
  it("covers every fixture pattern (if this fails, regenerate with tests/py/generate_split_regex_oracle.py)", () => {
    const oraclePatternIds = new Set(fixture.cases.map(({ patternId }) => patternId));
    for (const { id } of patternsFixture.patterns) {
      expect(oraclePatternIds.has(id)).toBe(true);
    }
  });

  it.each(fixture.cases.filter((oracleCase) => !oracleCase.knownDivergence))("matches Python Split output: $name", (oracleCase) => {
    const preTokenizer = create_split(oracleCase);
    for (const { input, tokens } of oracleCase.expected) {
      expect(preTokenizer.pre_tokenize_text(input)).toEqual(tokens);
    }
  });

  // These cases pin behavior we knowingly cannot reproduce (see "Regex compatibility" in the
  // README). If one starts matching Python, the divergence has been fixed: clear its
  // `knownDivergence` flag in splitRegexPatterns.json and regenerate the oracle.
  it.each(fixture.cases.filter((oracleCase) => oracleCase.knownDivergence))("documents known divergence from Python: $name", (oracleCase) => {
    const preTokenizer = create_split(oracleCase);
    const outputs = oracleCase.expected.map(({ input }) => preTokenizer.pre_tokenize_text(input));
    expect(outputs).not.toEqual(oracleCase.expected.map(({ tokens }) => tokens));
  });
});
